### ISSUE TITLE
pterohost

### ISSUE THREAD

**Issue by JustDoom** [SpiritenHasArrived/MC#3]
idk if you will add ones in other languages but here
https://pterohost.com/

**Comment by SpiritenHasArrived** [comment]
ooh, ill add em - never came up in any of my searches. just'll take a bit to get a proper translation of what I need (also if I need to contact support for anything its a no go due to language constaints)

**Comment by SpiritenHasArrived** [comment]
updated server hosts listed with them + 9 other hosts (including Whost who is completely in Spanish)
